version: '3.9'

services:
  db:
    image: postgres:latest
    env_file:
      - ./conf/db.env
    container_name: pg_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  adminer:
    image: adminer:latest 
    container_name: pg_adminer
    ports: 
    - "8085:8080"

  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./conf/minio.env
    volumes:
      - ./conf/minio_data:/data
      - ./conf/mc:/root/.mc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pg_data:
